### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by fenryxo** [tiliado/valacef#1]
@excieve: Reticketed from https://github.com/tiliado/nuvolaruntime/issues/91#issuecomment-351032809

> Although UI feels a little sluggish (no GPU acceleration?)

**Comment by fenryxo** [comment]
This needs to be investigated further.

**Comment by excieve** [comment]
To clarify by "a little sluggish" I mean visibly slower than the same thing in the real Chrome browser but perfectly usable. Also checked about GPU acceleration — there's a `/app/lib/valacef/ValacefSubprocess` using the GPU resources so that appears to be enabled.

**Comment by fenryxo** [comment]
From the testing of Nuvola/CEF with NVidia GTX 107 (driver 387.34):

> However, CPU usage is high (80-90%) when interacting with the UI, which is visibly less responsive than Chrome, RAM usage is rather high by ValacefSubprocess (around 500MB) and nuvola-app-google-play-music at about 150MB. CPU usage is also high (40-50%) during the playback and persists when the window is closed (playing in the background).
>
> I have tested GPM in Google Chrome 63 and there are no such symptoms — CPU usage is within 10% usually, it's a bit hard to measure the RAM usage but it seems to be around 270MB by various processes, the UI is visibly faster too. I've made two screencasts with rendering FPS dev tool enabled to compare the framerate — they're attached. You can see that in Nuvola it's around 30-40fps and in Chrome around 60fps (probably vsynced) when actively using the UI.
>
> Note that in both cases GPU is apparently being used but hardware rasterisation is disabled (due to blacklisting by default on Linux I guess).
>
> This is on Fedora 27 with NVidia GTX 1070, which seems to be detected by Nuvola:
Runner: [DEBUG Δ000233us Nuvola] Graphics.vala:36: Nvidia 387.34, i915 0, bumblebeed 0 => ignored 0

**Comment by excieve** [comment]
Tested it on Elementary OS 0.4.1 with Intel HD 4600 (mesa 17.0.7). Having exactly the same issues as my Fedora/NVidia report above.

**Comment by fenryxo** [comment]
Bad performance also with "Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller [8086:0412] (rev 06)"

Chrome applies following GPU workarounds (chrome://gpu):

- adjust_src_dst_region_for_blitframebuffer
- clear_uniforms_before_first_program_use
- count_all_in_varyings_packing
- decode_encode_srgb_for_generatemipmap
- disable_framebuffer_cmaa
- disable_post_sub_buffers_for_onscreen_surfaces
- msaa_is_slow
- scalarize_vec_and_mat_constructor_args

Nuvola/CEF only these:

- clear_uniforms_before_first_program_use
- count_all_in_varyings_packing
- decode_encode_srgb_for_generatemipmap
- disable_framebuffer_cmaa
- disable_post_sub_buffers_for_onscreen_surfaces
- scalarize_vec_and_mat_constructor_args

It seems that Chromium in the flatpak sandbox fails to detect GPU vendor and product id: `VENDOR = 0x8086, DEVICE= 0x0412` in Chrome (same as in `lspci`), `VENDOR = 0x0000, DEVICE= 0x0000` in Nuvola/Chromium.

**Comment by fenryxo** [comment]
Well, Chrome does not like the graphics card on my main development machine: "ATI/AMD cards with older drivers in Linux are crash-prone" resulting in no hardware acceleration at all.

**Comment by fenryxo** [comment]
Chrome uses libpci to get GPU vendor and product id, but it is not included in the GNOME Plarform runtime.

**Comment by fenryxo** [comment]
I get 60 fps with Nuvola 4.9.76 and Intel Ivybridge card. @excieve, could you check it is also ok with your NVidia & Intel cards?

**Comment by excieve** [comment]
Works great for me on both NVidia and Intel. The UI is very responsive, no significant CPU usage, seems to use less RAM too. Thanks!

**Comment by fenryxo** [comment]
Awesome :+1:
