### ISSUE TITLE
Upgrade to Chrome 78

### ISSUE THREAD

**Issue by fenryxo** [tiliado/valacef#17]
* Released Oct 2019
* [CEF branch 3904](https://bitbucket.org/chromiumembedded/cef/branch/3904)
* Chrome 75 was #16

**Comment by fenryxo** [comment]
There are issues with the network connection. See also [Network stuck in app using 3809](https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=17032).

**Comment by fenryxo** [comment]
Let's skip 76 & 77 as stable 78 is out.

**Comment by fenryxo** [comment]
Still no luck with Chrome 78 :-(

**Comment by fenryxo** [comment]
We could switch to QtWebEngine but it would take a while...

**Comment by gavr123456789** [comment]
(((

**Comment by fenryxo** [comment]
The plan is to keep Nuvola Vala/GTK and use QtWebEngine in an external process.

**Comment by gavr123456789** [comment]
Nice to hear, It will be very interesting. If you plan to interact with the Qt code from Vala, I recommend you to look at how the Qt bindings for Crystal and Go were made. They literally generated a C API for everything and communicated through it. This might work for Vala. (And actually quite a lot of people want to use Qt from Vala, but I think it doesn't make sense)

**Comment by jiri-janousek** [comment]
Closing in favor of tiliado/nuvolaruntime#583
